### ISSUE TITLE
data creation script

### ISSUE THREAD

**Issue by yipcma** [RMHogervorst/TNG#1]
Hi @RMHogervorst,

Wonderful compilation of data! I wonder if you could share the data cleaning script you used for the data. I'm not exactly sure about some of the variables and would love to follow your process of data preparation.

Thank you very much :)

**Comment by RMHogervorst** [comment]
Hi yipcma,

I think all my code is in this repo: https://github.com/RMHogervorst/startrekTNGdataset in the R folder.

I might have used some dutch in some files, so don't hesitate to ask me for translations or such. Glad you liked it!

Also: I didn't really optimize the scraping process because I only ran it once and it took like half an hour to do. If you have improvements I would love to hear them.

Good luck!

**Comment by RMHogervorst** [comment]
This is the scraping script: https://github.com/RMHogervorst/startrekTNGdataset/blob/master/R/textanalyses.R other files are not needed

**Comment by yipcma** [comment]
Thanks a lot :) This is very exciting indeed. What are you working on lately?

**Comment by RMHogervorst** [comment]
I currently work on bugfixes and improvements for [badgecreatr](https://github.com/RMHogervorst/badgecreatr) and I want to make it easier for people to document their datasets with summarize_dat https://github.com/RMHogervorst/summarize_dat/ Oh and several other small projects ;)
